name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # `main` ブランチに push されたら実行

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub リポジトリを取得
        uses: actions/checkout@v3

      - name: Python 環境をセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 依存関係をインストール
        run: pip install -r project1/requirements.txt

      - name: 自動テストを実行
        run: pytest
